version: "3.1"
services:
  mariadb:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    image: mariadb:11.3.2-jammy
    container_name: mariadb
    hostname: mysql-server
    user: root
    #restart: always
    ports:
      - 10001:3306
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./mariadb/logs:/var/log/mysql
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_bin',
      '--lower_case_table_names=1',
      '--max_connections=6000',
      '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
      '--symbolic-links=0',
      '--log-bin=/var/lib/mysql/mysql-bin',
      '--server-id=123654',
      '--expire_logs_days=5',
      '--binlog-format=ROW',
      '--max_allowed_packet=256M',
      '--group_concat_max_len=10485760',
      '--tmp_table_size=256M',
      '--max_heap_table_size=256M',
      '--innodb_buffer_pool_size=8G',
      '--relay-log=mysql-server-relay-bin'
    ]
